(function(MaSeedData) {

    MaSeedData.MailUser = [
        { Mail__Id:1,  User__Id:2, IsSender:true },
        { Mail__Id:2,  User__Id:2, IsSender:false  },
        { Mail__Id:3,  User__Id:2, IsSender:true  },
        { Mail__Id:4,  User__Id:2, IsSender:true  },
        { Mail__Id:5,  User__Id:2, IsSender:false  },
        { Mail__Id:6,  User__Id:2, IsSender:false  },
        { Mail__Id:7,  User__Id:2, IsSender:true  },
        { Mail__Id:8,  User__Id:2, IsSender:true  },
        { Mail__Id:9,  User__Id:2, IsSender:true  },
        { Mail__Id:10, User__Id:2, IsSender:true  },
        { Mail__Id:11, User__Id:2, IsSender:false  },
        { Mail__Id:12, User__Id:2, IsSender:true  },
        { Mail__Id:13, User__Id:2, IsSender:true  },
        { Mail__Id:14, User__Id:2, IsSender:false  },
        { Mail__Id:15, User__Id:2, IsSender:false  },
        { Mail__Id:16, User__Id:2, IsSender:true  },
        { Mail__Id:17, User__Id:2, IsSender:true  },
        { Mail__Id:18, User__Id:2, IsSender:true  },
        { Mail__Id:19, User__Id:2, IsSender:true  },
        { Mail__Id:1,  User__Id:1, IsSender:false },
        { Mail__Id:2,  User__Id:1, IsSender:true  },
        { Mail__Id:3,  User__Id:1, IsSender:false  },
        { Mail__Id:4,  User__Id:1, IsSender:false  },
        { Mail__Id:5,  User__Id:1, IsSender:true  },
        { Mail__Id:6,  User__Id:1, IsSender:true  },
        { Mail__Id:7,  User__Id:1, IsSender:false  },
        { Mail__Id:8,  User__Id:1, IsSender:false  },
        { Mail__Id:9,  User__Id:1, IsSender:false  },
        { Mail__Id:10, User__Id:1, IsSender:false  },
        { Mail__Id:11, User__Id:1, IsSender:true  },
        { Mail__Id:12, User__Id:1, IsSender:false  },
        { Mail__Id:13, User__Id:1, IsSender:false  },
        { Mail__Id:14, User__Id:1, IsSender:true  },
        { Mail__Id:15, User__Id:1, IsSender:true  },
        { Mail__Id:16, User__Id:1, IsSender:false  },
        { Mail__Id:17, User__Id:1, IsSender:false  },
        { Mail__Id:18, User__Id:1, IsSender:false  },
        { Mail__Id:19, User__Id:1, IsSender:false  }
    ];

})(window.MaSeedData = window.MaSeedData || {});